spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://qxia-cr.top:3306/db_study?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: user_study
    password: 123456

foo: foo version 1
